<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DocumentService.Core\DocumentService.Core.csproj" />
    <ProjectReference Include="..\DocumentService.Engines\DocumentService.Engines.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\templates\*.html" CopyToOutputDirectory="PreserveNewest" LinkBase="templates" />
    <None Include="..\..\samples\*.json" CopyToOutputDirectory="PreserveNewest" LinkBase="samples" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
